apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kengine-ingress-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kengine-ingress-controller.labels" . | nindent 4 }}
spec:
{{- with .Values.podDisruptionBudget }}
  {{- if .minAvailable }}
  minAvailable: {{ .minAvailable }}
  {{- end }}
  {{- if .maxUnavailable }}
  maxUnavailable: {{ .maxUnavailable }}
  {{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "kengine-ingress-controller.selectorLabels" . | nindent 6 }}
